#!/usr/bin/env bash
# tools/protocol/extract-vm-alloc.sh —— 在 devnet 容器内运行：
# 用 Avalanche CLI 的 --test-defaults 生成一份参考创世，提取其中 CLI 注入的 ValidatorManager 相关合约账户
# （带 `code` 的 alloc 条目），输出为 fixture JSON（research R-07 / tasks T013）。
#
# 同一份脚本也被 tests/e2e/vm-alloc-drift.test.sh 用来检测 CLI 版本漂移。
#
# 用法：extract-vm-alloc.sh [输出文件，默认 stdout]
#   需要：容器内 avalanche CLI、jq、已挂载的 /workspace/blockchain/protocol.json、本地网络无需运行。
set -euo pipefail

: "${KARMACHAIN_LIB:=/opt/karmachain/lib}"
source "${KARMACHAIN_LIB}/avalanche.sh"

OUT="${1:-}"
TMP_NAME="kcfixture$$"

cleanup() { av_blockchain_delete "${TMP_NAME}" >/dev/null 2>&1 || true; }
trap cleanup EXIT

# 1) 让 CLI 用测试默认值生成一份创世（chainId/token 来自 protocol.json，但只有合约账户会被提取）
av_blockchain_create_test_defaults "${TMP_NAME}" >/dev/null 2>&1

# 2) 读取创世：优先直接读 sidecar 旁的 genesis.json，避免 describe 输出里的终端控制字符
GENESIS_FILE="${AVALANCHE_CLI_HOME}/subnets/${TMP_NAME}/genesis.json"
[ -r "${GENESIS_FILE}" ] || { echo "reference genesis not found at ${GENESIS_FILE}" >&2; exit 1; }

# 3) 提取带 code 的账户（ValidatorManager 逻辑合约、TransparentProxy、ProxyAdmin、ValidatorMessages 库），
#    余额置零、地址小写、按地址排序，保证输出确定性
CLI_VERSION="$(avalanche --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
jq -S --arg cli "v${CLI_VERSION}" --arg evm "$(proto_subnet_evm_ver)" --arg date "$(date -u +%Y-%m-%d)" '
  {
    "$comment": "GENERATED by tools/protocol/extract-vm-alloc.sh — ValidatorManager contract accounts injected by Avalanche CLI into a Subnet-EVM genesis. Do not edit by hand; re-extract when avalancheCliVersion changes.",
    extractedFrom: {
      avalancheCliVersion: $cli,
      subnetEvmVersion: $evm,
      command: "avalanche blockchain create <tmp> --evm --test-defaults --proof-of-authority ...",
      date: $date
    },
    warpConfig: (.config.warpConfig | del(.blockTimestamp)),
    alloc: (
      .alloc
      | to_entries
      | map(select(.value.code != null))
      | map({ key: (.key | ascii_downcase | ltrimstr("0x")),
              value: ({ balance: "0x0", code: .value.code, nonce: (.value.nonce // "0x1") }
                      + (if .value.storage then { storage: .value.storage } else {} end)) })
      | sort_by(.key)
      | from_entries
    )
  }' "${GENESIS_FILE}" > "${OUT:-/dev/stdout}"

if [ -n "${OUT}" ]; then
  echo "fixture written: ${OUT} ($(jq '.alloc | length' "${OUT}") contract accounts)" >&2
fi
